name: Build, Test, and Publish NuGet Packages

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/AiHedgeFund.sln

      - name: Build projects and generate NuGet packages
        run: dotnet build src/AiHedgeFund.sln -c Release --no-restore

      - name: Push NuGet packages
        run: |
          dotnet nuget push **/bin/Release/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate

      - name: Generate release notes
        id: changelog
        run: |
          REPO_URL="https://github.com/${{ github.repository }}"
          {
            echo "changelog<<EOF"
            echo "### Changelog"
            echo ""
            git log --pretty=format:"- \`%s\` ([%h](${REPO_URL}/commit/%H))" $(git describe --tags --abbrev=0)^..HEAD
            echo ""
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Upload GitHub release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
