name: Build, Test, and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: .
          fetch-depth: 0  # Enables changelog generation from commit history

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/AiHedgeFund.sln

      - name: Build solution
        run: dotnet build src/AiHedgeFund.sln --configuration Release --no-restore

      # - name: Show contents of bin folder
      #   run: ls -R src/AiHedgeFund.Tests/bin

      # - name: Run tests
      #   run: dotnet test src/AiHedgeFund.Tests/AiHedgeFund.Tests.csproj --no-build --verbosity normal

      - name: Publish console app
        run: dotnet publish src/AiHedgeFund.Console/AiHedgeFund.Console.csproj -c Release -o out

      - name: Archive release output
        run: zip -r release-artifacts.zip out

      - name: Generate release notes
        id: changelog
        run: |
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0)^..HEAD > changelog.txt
          echo "changelog=$(cat changelog.txt)" >> $GITHUB_OUTPUT      

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: release-artifacts.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
